"""ASS subtitle renderer"""

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Callable, Optional, Tuple

from PIL import Image

from videocaptioner.config import CACHE_PATH, FONTS_PATH, RESOURCE_PATH
from videocaptioner.core.entities import SubtitleLayoutEnum
from videocaptioner.core.synthesis.ffmpeg_env import get_ffmpeg_path
from videocaptioner.core.utils.logger import setup_logger

from .ass_utils import auto_wrap_ass_file

if TYPE_CHECKING:
    from videocaptioner.core.asr.asr_data import ASRData
    from videocaptioner.core.synthesis.models import EncodeSettings
    from videocaptioner.core.synthesis.runner import SynthesisControl

logger = setup_logger("subtitle.ass")
ReferenceHeight = int | float | str | None
ASS_TEMPLATE = """[Script Info]
; Script generated by VideoCaptioner
ScriptType: v4.00+
WrapStyle: 1
ScaledBorderAndShadow: yes
PlayResX: {video_width}
PlayResY: {video_height}

{style_str}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
{dialogue}
"""


def _normalize_reference_height(reference_height: ReferenceHeight) -> int:
    """Keep reference-height based scaling from dividing by zero."""
    if reference_height is None:
        return 720
    try:
        return max(1, int(reference_height))
    except (TypeError, ValueError):
        return 720


def _check_cuda_available() -> bool:
    """检查 CUDA 是否可用"""
    from videocaptioner.core.utils.video_utils import check_cuda_available
    return check_cuda_available()


def _scale_ass_style(style_str: str, scale_factor: float) -> str:
    """
    缩放 ASS 样式中的数值参数

    Args:
        style_str: 原始 ASS 样式字符串（按样式基准分辨率设计）
        scale_factor: 缩放因子

    Returns:
        缩放后的 ASS 样式字符串
    """
    if scale_factor == 1.0:
        return style_str

    lines = style_str.split("\n")
    scaled_lines = []

    for line in lines:
        if line.startswith("Style:"):
            parts = line.split(",")
            if len(parts) >= 23:
                # parts[2]: Fontsize
                parts[2] = str(int(float(parts[2]) * scale_factor))
                # parts[13]: Spacing
                parts[13] = str(float(parts[13]) * scale_factor)
                # parts[16]: Outline
                parts[16] = str(float(parts[16]) * scale_factor)
                # parts[17]: Shadow
                parts[17] = str(float(parts[17]) * scale_factor)
                # parts[19]/[20]: MarginL/MarginR
                parts[19] = str(int(float(parts[19]) * scale_factor))
                parts[20] = str(int(float(parts[20]) * scale_factor))
                # parts[21]: MarginV (垂直间距)
                parts[21] = str(int(float(parts[21]) * scale_factor))
                line = ",".join(parts)
        scaled_lines.append(line)

    return "\n".join(scaled_lines)


def render_ass_preview(
    style_str: str,
    preview_text: Tuple[str, Optional[str]],
    bg_image_path: str,
    width: Optional[int] = None,
    height: Optional[int] = None,
    reference_height: int = 720,
) -> str:
    """
    生成 ASS 样式字幕预览图

    Args:
        style_str: ASS 样式字符串（包含 PlayResY）
        preview_text: (原文, 译文) 元组，译文可以为 None
        bg_image_path: 背景图片路径
        width: 图片宽度（None=从bg_image_path自动获取）
        height: 图片高度（None=从bg_image_path自动获取）
        reference_height: 样式设计基准高度
    Returns:
        生成的预览图路径
    """
    # 自动获取图片尺寸
    if width is None or height is None:
        bg_path = Path(bg_image_path)
        if bg_path.exists():
            with Image.open(bg_path) as img:
                actual_width, actual_height = img.size
                width = width or actual_width
                height = height or actual_height
        else:
            width = width or 1920
            height = height or 1080

    original_text, translate_text = preview_text

    # 构建对话行
    if translate_text:
        dialogue = [
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Secondary,,0,0,0,,{translate_text}",
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{original_text}",
        ]
    else:
        dialogue = [
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{original_text}"
        ]

    # 生成 ASS 内容
    ass_content = ASS_TEMPLATE.format(
        style_str=style_str,
        dialogue=os.linesep.join(dialogue),
        video_width=width,
        video_height=height,
    )

    # 根据图片高度和样式基准高度自动缩放样式
    reference_height = _normalize_reference_height(reference_height)
    scale_factor = height / reference_height
    style_str = _scale_ass_style(style_str, scale_factor)

    # 重新生成缩放后的 ASS 内容
    ass_content = ASS_TEMPLATE.format(
        style_str=style_str,
        dialogue=os.linesep.join(dialogue),
        video_width=width,
        video_height=height,
    )

    # 创建临时 ASS 文件
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ass", delete=False, encoding="utf-8"
    ) as f:
        f.write(ass_content)
        temp_ass_path = f.name

    processed_ass = temp_ass_path
    try:
        # 自动换行处理
        processed_ass = auto_wrap_ass_file(temp_ass_path)

        # 确保背景图片存在
        bg_path_obj = Path(bg_image_path)
        if not bg_path_obj.exists():
            # 使用默认黑色背景
            default_bg = RESOURCE_PATH / "assets" / "default_bg.png"
            if not default_bg.exists():
                default_bg.parent.mkdir(parents=True, exist_ok=True)
                # 生成黑色背景
                subprocess.run(
                    [
                        get_ffmpeg_path(),
                        "-f",
                        "lavfi",
                        "-i",
                        f"color=c=black:s={width}x{height}",
                        "-frames:v",
                        "1",
                        str(default_bg),
                    ],
                    capture_output=True,
                    creationflags=(
                        getattr(subprocess, "CREATE_NO_WINDOW", 0)
                        if os.name == "nt"
                        else 0
                    ),
                )
            bg_path_obj = default_bg

        # 生成预览图
        output_path = CACHE_PATH / "ass_preview.png"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # 处理 ASS 文件路径（Windows 兼容）
        ass_file_escaped = processed_ass.replace("\\", "/").replace(":", r"\:")

        # 添加内置字体目录支持
        fonts_dir_escaped = str(FONTS_PATH).replace("\\", "/").replace(":", r"\:")

        cmd = [
            get_ffmpeg_path(),
            "-y",
            "-i",
            str(bg_path_obj),
            "-vf",
            f"ass='{ass_file_escaped}':fontsdir='{fonts_dir_escaped}'",
            "-frames:v",
            "1",
            str(output_path),
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            creationflags=(
                getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
            ),
        )

        if result.returncode != 0:
            logger.error(f"FFmpeg preview generation failed: {result.stderr}")

        return str(output_path)

    finally:
        # 清理临时文件
        Path(temp_ass_path).unlink(missing_ok=True)
        if processed_ass != temp_ass_path:
            Path(processed_ass).unlink(missing_ok=True)


def _get_video_resolution(video_path: str) -> Tuple[int, int]:
    """获取视频分辨率"""
    result = subprocess.run(
        [get_ffmpeg_path(), "-i", video_path],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        creationflags=(
            getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
        ),
    )

    # 从 ffmpeg 输出中解析分辨率
    pattern = r"(\d{2,5})x(\d{2,5})"
    match = re.search(pattern, result.stderr or "")
    if match:
        return int(match.group(1)), int(match.group(2))
    return 1920, 1080  # 默认返回 1080P


def _render_via_builder(
    *,
    video_path: str,
    output_path: str,
    video_filter: str,
    settings: "EncodeSettings",
    progress_callback: Optional[Callable] = None,
    control: "Optional[SynthesisControl]" = None,
) -> None:
    """新引擎路径：结构化编码设置 -> 集中命令构建器 -> 执行（见方案 §7/§16）。"""
    from videocaptioner.core.synthesis import media_probe, runner
    from videocaptioner.core.synthesis.command_builder import (
        build_ffmpeg_command,
        build_two_pass_commands,
        supports_two_pass,
    )
    from videocaptioner.core.synthesis.encoder_catalog import get_encoder_spec
    from videocaptioner.core.synthesis.ffmpeg_env import supports_fps_mode

    probe = None
    if settings.preserve_color or settings.target_height:
        probe = media_probe.probe(video_path, source=settings.ffmpeg_source)

    # 分辨率下缩：以探测高度为唯一基准（§16.7/§16.9），scale 置于 ass 之后
    vf = video_filter
    if probe is not None and settings.target_height and probe.height:
        eff_h = probe.effective_height(settings.target_height)
        if eff_h and eff_h < probe.height:
            vf = f"{vf},scale=-2:{eff_h}"

    ffmpeg = get_ffmpeg_path(settings.ffmpeg_source)

    # 解码加速：硬件编码器交给构建器按后端推导；CPU 编码器沿用机会性 CUDA 解码（§16.3）
    decode_hwaccel = None
    spec = get_encoder_spec(settings.video_encoder)
    if (spec is None or not spec.is_hardware) and _check_cuda_available():
        decode_hwaccel = "cuda"

    vfr_flag = "-fps_mode" if supports_fps_mode(ffmpeg) else "-vsync"
    total = (probe.duration_seconds or None) if probe else None

    if supports_two_pass(settings):
        passdir = tempfile.mkdtemp(prefix="vc_2pass_")
        passlog = os.path.join(passdir, "log")
        p1, p2 = build_two_pass_commands(
            ffmpeg=ffmpeg, input_path=video_path, output_path=output_path,
            video_filter=vf, settings=settings, probe=probe, passlog=passlog,
            decode_hwaccel=decode_hwaccel, vfr_flag=vfr_flag,
        )
        try:
            runner.run_two_pass(p1, p2, progress_callback=progress_callback, total_duration=total, control=control)
        finally:
            shutil.rmtree(passdir, ignore_errors=True)
    else:
        cmd = build_ffmpeg_command(
            ffmpeg=ffmpeg, input_path=video_path, output_path=output_path,
            video_filter=vf, settings=settings, probe=probe,
            decode_hwaccel=decode_hwaccel, vfr_flag=vfr_flag,
        )
        runner.run_encode(cmd, progress_callback=progress_callback, total_duration=total, control=control)


def render_ass_video(
    video_path: str,
    asr_data: "ASRData",
    output_path: str,
    style_str: str,
    layout: SubtitleLayoutEnum,
    crf: int = 23,
    preset: str = "medium",
    progress_callback: Optional[Callable] = None,
    reference_height: int = 720,
    encode_settings: "Optional[EncodeSettings]" = None,
    control: "Optional[SynthesisControl]" = None,
) -> None:
    """
    渲染 ASS 样式字幕到视频（硬字幕）

    Args:
        video_path: 输入视频路径
        asr_data: 字幕数据
        output_path: 输出视频路径
        style_str: ASS 样式字符串（包含 PlayResY）
        layout: 字幕布局
        crf: 视频质量参数 (0-51，越小越好)
        preset: FFmpeg 编码预设
        progress_callback: 进度回调 (progress: str, message: str) -> None
        reference_height: 样式设计基准高度
    """
    # 检查字幕数据是否为空
    if not asr_data or not asr_data.segments:
        raise ValueError("Empty subtitle data, cannot render video")

    # 获取视频分辨率
    width, height = _get_video_resolution(video_path)

    # 根据视频高度和样式基准高度自动缩放样式
    reference_height = _normalize_reference_height(reference_height)
    scale_factor = height / reference_height
    style_str = _scale_ass_style(style_str, scale_factor)

    # 生成临时 ASS 文件（传入实际视频分辨率）
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ass", delete=False, encoding="utf-8"
    ) as temp_file:
        ass_content = asr_data.to_ass(
            style_str=style_str,
            layout=layout,
            save_path=None,
            video_width=width,
            video_height=height,
        )
        temp_file.write(ass_content)
        temp_ass_path = temp_file.name

    processed_subtitle = temp_ass_path
    try:
        # 自动换行处理
        processed_subtitle = auto_wrap_ass_file(temp_ass_path)

        # 转义字幕路径
        subtitle_path_escaped = Path(processed_subtitle).as_posix().replace(":", r"\:")

        # 构建 FFmpeg Command
        vcodec = "libx264"
        if Path(output_path).suffix.lower() == ".webm":
            vcodec = "libvpx-vp9"
            logger.debug("WebM format, using libvpx-vp9")

        # 添加内置字体目录支持
        fonts_dir_escaped = FONTS_PATH.as_posix().replace(":", r"\:")

        # 统一使用 ass 滤镜
        vf = f"ass='{subtitle_path_escaped}':fontsdir='{fonts_dir_escaped}'"

        # 新引擎路径：结构化编码设置存在时走集中命令构建器（见 ADR 0007）
        if encode_settings is not None:
            _render_via_builder(
                video_path=video_path,
                output_path=output_path,
                video_filter=vf,
                settings=encode_settings,
                progress_callback=progress_callback,
                control=control,
            )
            return

        # 检查 CUDA 是否可用
        use_cuda = _check_cuda_available()
        cmd = [get_ffmpeg_path()]
        if use_cuda:
            logger.debug("Using CUDA acceleration")
            cmd.extend(["-hwaccel", "cuda"])

        cmd.extend(
            [
                "-i",
                video_path,
                "-acodec",
                "copy",
                "-vcodec",
                vcodec,
                "-crf",
                str(crf),
                "-preset",
                preset,
                "-vf",
                vf,
                "-y",
                output_path,
            ]
        )

        cmd_str = subprocess.list2cmdline(cmd)
        logger.debug(f"FFmpeg ASS render cmd: {cmd_str}")

        # 执行 FFmpeg
        process = None
        try:
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
                creationflags=(
                    getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
                ),
            )

            # 实时Reading输出并调用回调
            total_duration = None
            current_time = 0

            while True:
                output_line = process.stderr.readline()
                if not output_line or (process.poll() is not None):
                    break
                if not progress_callback:
                    continue

                # 解析总时长
                if total_duration is None:
                    duration_match = re.search(
                        r"Duration: (\d{2}):(\d{2}):(\d{2}\.\d{2})", output_line
                    )
                    if duration_match:
                        h, m, s = map(float, duration_match.groups())
                        total_duration = h * 3600 + m * 60 + s

                # 解析当前处理时间
                time_match = re.search(
                    r"time=(\d{2}):(\d{2}):(\d{2}\.\d{2})", output_line
                )
                if time_match:
                    h, m, s = map(float, time_match.groups())
                    current_time = h * 3600 + m * 60 + s

                # 计算进度百分比
                if total_duration:
                    progress = (current_time / total_duration) * 100
                    progress_callback(f"{round(progress)}", "正在合成")

            if progress_callback:
                progress_callback("100", "合成完成")

            # 检查Return code
            return_code = process.wait()
            if return_code != 0:
                error_info = process.stderr.read()
                logger.error("FFmpeg ASS rendering failed")
                logger.error(f"Return code: {return_code}")
                logger.error(f"Command: {cmd_str}")
                if error_info:
                    logger.error(f"Error output: {error_info}")
                raise Exception(f"FFmpeg Return code: {return_code}")

            logger.debug("ASS subtitle rendering complete")

        except subprocess.SubprocessError as e:
            logger.error("FFmpeg process error")
            logger.error(f"Error: {str(e)}")
            if process and process.poll() is None:
                process.kill()
            raise
        except Exception as e:
            logger.error(f"ASS subtitle rendering error: {str(e)}")
            if process and process.poll() is None:
                process.kill()
            raise

    finally:
        # 清理临时文件
        Path(temp_ass_path).unlink(missing_ok=True)
        if processed_subtitle != temp_ass_path:
            Path(processed_subtitle).unlink(missing_ok=True)
