"""Subtitle reading-speed policy, load model, and M3 metrics."""

from .alignment import (
    AlignmentConfig,
    AlignmentPreflight,
    AlignmentRunResult,
    AlignmentWindowPlan,
    align_timing_windows,
    alignment_config_fingerprint,
    load_or_align_timing,
    plan_alignment_windows,
    preflight_alignment,
)
from .metrics import (
    AdjacentJump,
    CueSpeedSample,
    SpeedMetrics,
    calculate_adjacent_jump,
    calculate_hard_deficit,
    calculate_speed_metrics,
    calculate_speed_spread,
    weighted_percentile,
)
from .policy import SpeedPolicy, SpeedPreset, available_speed_presets, get_speed_policy
from .profiles import (
    DEFAULT_SPEED_PROFILES_PATH,
    BuiltinProfileError,
    ProfileConflictError,
    ProfileNotFoundError,
    ProfileValidationError,
    SpeedProfile,
    SpeedProfileStore,
    load_speed_profile,
    resolve_speed_policy,
)
from .reading_load import (
    GraphemeKind,
    ReadingLoad,
    ReadingUnits,
    calculate_reading_load,
    classify_grapheme,
    count_reading_units,
    split_graphemes,
)
from .validation import (
    IndependentSemanticReviewer,
    ReviewDecision,
    SemanticReviewRequest,
    SemanticReviewResponse,
    SemanticValidationResult,
    SemanticWindow,
    ValidationReason,
    ValidationReasonCode,
    ValidationStatus,
    resolve_semantic_review,
    validate_semantic_window,
)

__all__ = [
    "AdjacentJump",
    "AlignmentConfig",
    "AlignmentPreflight",
    "AlignmentRunResult",
    "AlignmentWindowPlan",
    "BuiltinProfileError",
    "CueSpeedSample",
    "DEFAULT_SPEED_PROFILES_PATH",
    "GraphemeKind",
    "IndependentSemanticReviewer",
    "ProfileConflictError",
    "ProfileNotFoundError",
    "ProfileValidationError",
    "ReadingLoad",
    "ReadingUnits",
    "ReviewDecision",
    "SemanticReviewRequest",
    "SemanticReviewResponse",
    "SemanticValidationResult",
    "SemanticWindow",
    "SpeedMetrics",
    "SpeedPolicy",
    "SpeedProfile",
    "SpeedProfileStore",
    "SpeedPreset",
    "ValidationReason",
    "ValidationReasonCode",
    "ValidationStatus",
    "available_speed_presets",
    "alignment_config_fingerprint",
    "align_timing_windows",
    "calculate_adjacent_jump",
    "calculate_hard_deficit",
    "calculate_reading_load",
    "calculate_speed_metrics",
    "calculate_speed_spread",
    "classify_grapheme",
    "count_reading_units",
    "get_speed_policy",
    "load_speed_profile",
    "load_or_align_timing",
    "plan_alignment_windows",
    "preflight_alignment",
    "resolve_semantic_review",
    "resolve_speed_policy",
    "split_graphemes",
    "validate_semantic_window",
    "weighted_percentile",
]
