import os
import subprocess
import sys


def _run_qt_script(script: str) -> None:
    env = os.environ.copy()
    env["QT_QPA_PLATFORM"] = "offscreen"
    result = subprocess.run(
        [sys.executable, "-c", script],
        env=env,
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_home_workflow_places_postprocess_between_translation_and_synthesis():
    _run_qt_script(
        """
from PyQt5.QtWidgets import QApplication
from videocaptioner.ui.view.home_interface import HomeInterface

app = QApplication([])
widget = HomeInterface()
pages = [widget.stackedWidget.widget(i).objectName() for i in range(widget.stackedWidget.count())]
assert pages == [
    'TaskCreationInterface',
    'TranscriptionInterface',
    'SubtitleInterface',
    'PostprocessInterface',
    'VideoSynthesisInterface',
]
widget.pivot.items['PostprocessInterface'].click()
app.processEvents()
assert widget.stackedWidget.currentWidget() is widget.postprocess_interface
assert not hasattr(widget.subtitle_optimization_interface, 'speed_optimize_button')
assert not hasattr(widget.subtitle_optimization_interface, 'associate_media_button')
widget.close()
"""
    )


def test_postprocess_page_edits_selected_profile_immediately(tmp_path):
    profile_path = repr(str(tmp_path / "profiles.json"))
    _run_qt_script(
        f"""
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.postprocess_interface import PostprocessInterface

app = QApplication([])
store = PostprocessProfileStore({profile_path})
widget = PostprocessInterface(profile_store=store)
widget.select_profile('balanced')
widget.set_mode('analyze')
app.processEvents()
assert store.get('balanced').config.speed_mode == 'analyze'
widget.close()
"""
    )


def test_setting_title_uses_theme_aware_colors():
    _run_qt_script(
        """
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QApplication
from qfluentwidgets import Theme, TitleLabel, setTheme
from videocaptioner.ui.view.setting_interface import SettingInterface

app = QApplication([])
setTheme(Theme.LIGHT)
widget = SettingInterface()
app.processEvents()
assert isinstance(widget.settingLabel, TitleLabel)
assert widget.settingLabel.lightColor == QColor(0, 0, 0)
assert 'color: white' not in widget.styleSheet()
setTheme(Theme.DARK)
app.processEvents()
assert widget.settingLabel.darkColor == QColor(255, 255, 255)
widget.close()
"""
    )


def test_postprocess_settings_tabs_keep_dark_theme_background_transparent(tmp_path):
    profile_path = repr(str(tmp_path / "profiles.json"))
    _run_qt_script(
        f"""
from PyQt5.QtGui import QPalette
from PyQt5.QtWidgets import QApplication
from qfluentwidgets import Theme, setTheme
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.speed_setting_interface import PostprocessSettingInterface

app = QApplication([])
setTheme(Theme.DARK)
widget = PostprocessSettingInterface(
    profile_store=PostprocessProfileStore({profile_path})
)
widget.show()
app.processEvents()
for tab in widget._tabs.values():
    assert not tab.viewport().autoFillBackground()
    assert not tab.scrollWidget.autoFillBackground()
    assert tab.scrollWidget.palette().color(QPalette.Window).alpha() == 0
widget.close()
"""
    )


def test_postprocess_imports_working_draft_and_requires_layout_confirmation(tmp_path):
    subtitle = tmp_path / "plain.srt"
    subtitle.write_text(
        "1\n00:00:00,000 --> 00:00:02,000\nA single line caption\n",
        encoding="utf-8",
    )
    profile_path = repr(str(tmp_path / "profiles.json"))
    subtitle_path = repr(str(subtitle))
    _run_qt_script(
        f"""
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.postprocess_interface import PostprocessInterface

app = QApplication([])
widget = PostprocessInterface(profile_store=PostprocessProfileStore({profile_path}))
widget.load_subtitle({subtitle_path})
assert widget.model.rowCount() == 1
assert widget._structure_confirmation_required
assert not widget.start_button.isEnabled()
widget.layout_combo.setCurrentIndex(widget.layout_combo.findData('single'))
app.processEvents()
assert not widget._structure_confirmation_required
assert widget.start_button.isEnabled()
widget.close()
"""
    )


def test_video_captioner_ass_metadata_is_trusted(tmp_path):
    subtitle = tmp_path / "trusted.ass"
    subtitle.write_text(
        """[Script Info]
; Script generated by VideoCaptioner
; SubtitleLayout: TRANSLATE_ON_TOP
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,译文
Dialogue: 0,0:00:00.00,0:00:02.00,Secondary,,0,0,0,,Original
""",
        encoding="utf-8",
    )
    profile_path = repr(str(tmp_path / "profiles.json"))
    subtitle_path = repr(str(subtitle))
    _run_qt_script(
        f"""
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.entities import SubtitleLayoutEnum
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.postprocess_interface import PostprocessInterface

app = QApplication([])
widget = PostprocessInterface(profile_store=PostprocessProfileStore({profile_path}))
widget.load_subtitle({subtitle_path})
assert widget.layout_combo.currentData() == 'translate_on_top'
assert not widget._structure_confirmation_required
assert widget.model._data['1']['original_subtitle'] == 'Original'
assert widget.model._data['1']['translated_subtitle'] == '译文'
assert widget._mode_for_layout(SubtitleLayoutEnum.ONLY_ORIGINAL).value == 'original_only'
assert widget._mode_for_layout(SubtitleLayoutEnum.ONLY_TRANSLATE).value == 'translate_only'
widget.close()
"""
    )


def test_postprocess_separates_input_roles_from_output_layout(tmp_path):
    subtitle = tmp_path / "bilingual.srt"
    subtitle.write_text(
        "1\n00:00:00,000 --> 00:00:02,000\n中文译文。\nEnglish original.\n",
        encoding="utf-8",
    )
    output = tmp_path / "postprocessed.srt"
    profile_path = repr(str(tmp_path / "profiles.json"))
    subtitle_path = repr(str(subtitle))
    output_path = repr(str(output))
    _run_qt_script(
        f"""
from pathlib import Path
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.postprocess_interface import PostprocessInterface

app = QApplication([])
widget = PostprocessInterface(profile_store=PostprocessProfileStore({profile_path}))
widget.load_subtitle({subtitle_path})
assert widget._structure_confirmation_required

# 输入第一行是译文；表格字段应恢复为英文原文、中文译文。
widget.layout_combo.setCurrentIndex(widget.layout_combo.findData('translate_on_top'))
app.processEvents()
assert widget.model._data['1']['original_subtitle'] == 'English original.'
assert widget.model._data['1']['translated_subtitle'] == '中文译文。'

# 输出布局是独立选择，能够真正交换可见上下行。
widget.output_layout_combo.setCurrentIndex(
    widget.output_layout_combo.findData('原文在上')
)
widget.primary_srt_path = {output_path}
assert widget.save_primary_srt(show_feedback=False)
lines = Path({output_path}).read_text(encoding='utf-8').splitlines()
assert lines[2] == 'English original.'
assert lines[3] == '中文译文。'
widget.close()
"""
    )


def test_postprocess_working_draft_save_clears_dirty_state(tmp_path):
    profile_path = repr(str(tmp_path / "profiles.json"))
    source_path = repr(str(tmp_path / "source.srt"))
    output_path = repr(str(tmp_path / "postprocessed-source.srt"))
    _run_qt_script(
        f"""
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.postprocess_interface import PostprocessInterface

app = QApplication([])
widget = PostprocessInterface(profile_store=PostprocessProfileStore({profile_path}))
widget.subtitle_path = {source_path}
widget.primary_srt_path = {output_path}
widget.model.update_all({{'1': {{'start_time': 0, 'end_time': 2000,
    'original_subtitle': 'Original', 'translated_subtitle': 'Translation'}}}})
assert not widget._dirty
index = widget.model.index(0, 2)
assert widget.model.setData(index, 'Updated original', Qt.EditRole)
assert widget._dirty
assert widget.save_primary_srt(show_feedback=False)
assert not widget._dirty
text = open({output_path}, encoding='utf-8').read()
assert 'Updated original' in text
widget.close()
"""
    )


def test_output_layout_change_marks_completed_draft_dirty(tmp_path):
    profile_path = repr(str(tmp_path / "profiles.json"))
    output_path = repr(str(tmp_path / "postprocessed.srt"))
    _run_qt_script(
        f"""
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.postprocess import PostprocessProfileStore
from videocaptioner.ui.view.postprocess_interface import PostprocessInterface

app = QApplication([])
widget = PostprocessInterface(profile_store=PostprocessProfileStore({profile_path}))
widget.model.update_all({{'1': {{'start_time': 0, 'end_time': 2000,
    'original_subtitle': 'Original', 'translated_subtitle': 'Translation'}}}})
widget.primary_srt_path = {output_path}
widget._set_dirty(False)
widget.output_layout_combo.setCurrentIndex(1)
app.processEvents()
assert widget._dirty
assert widget.status_label.text() == '有未保存的修改'
widget.close()
"""
    )


def test_translation_editor_separates_primary_save_from_delivery_export(tmp_path):
    source = tmp_path / "source.srt"
    source.write_text(
        "1\n00:00:00,000 --> 00:00:02,000\nOriginal\n",
        encoding="utf-8",
    )
    source_path = repr(str(source))
    export_path = repr(str(tmp_path / "delivery.vtt"))
    directory = repr(str(tmp_path))
    _run_qt_script(
        f"""
from pathlib import Path
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QFileDialog
from videocaptioner.ui.view.subtitle_interface import SubtitleInterface

app = QApplication([])
widget = SubtitleInterface()
widget.load_subtitle_file({source_path})
assert not widget._dirty
assert widget.model.setData(widget.model.index(0, 2), 'Edited', Qt.EditRole)
assert widget._dirty
assert widget.save_primary_srt(show_feedback=False)
assert not widget._dirty
primary = Path(widget.primary_srt_path)
assert primary.suffix == '.srt'
assert primary != Path({source_path})
QFileDialog.getSaveFileName = lambda *args, **kwargs: ({export_path}, '')
widget.on_export_format_clicked('vtt')
assert Path({export_path}).is_file()
assert widget.primary_srt_path == str(primary)
assert len(list(Path({directory}).glob('*.srt'))) == 2
widget.close()
"""
    )


def test_translation_editor_prefers_memory_handoff_and_snapshots_current_table(tmp_path):
    missing_path = repr(str(tmp_path / "does-not-exist.srt"))
    _run_qt_script(
        f"""
from PyQt5.QtCore import QObject, Qt, pyqtSignal
from PyQt5.QtWidgets import QApplication
from videocaptioner.core.asr.asr_data import ASRData, ASRDataSeg
from videocaptioner.core.entities import SubtitleTask
import videocaptioner.ui.view.subtitle_interface as subtitle_view

class FakeThread(QObject):
    finished = pyqtSignal(str, str)
    progress = pyqtSignal(int, str)
    update = pyqtSignal(dict)
    update_all = pyqtSignal(dict)
    error = pyqtSignal(str)
    def __init__(self, task):
        super().__init__()
        self.task = task
    def set_custom_prompt_text(self, _text): pass
    def start(self): pass
    def stop(self): pass

app = QApplication([])
subtitle_view.SubtitleThread = FakeThread
data = ASRData([ASRDataSeg('Memory original', 0, 2000, 'Memory translation')])
task = SubtitleTask(subtitle_path={missing_path}, input_data=data, need_next_task=False)
widget = subtitle_view.SubtitleInterface()
widget.set_task(task)
assert widget.model._data['1']['original_subtitle'] == 'Memory original'
assert widget.model.setData(widget.model.index(0, 2), 'Edited in table', Qt.EditRole)
widget.start_subtitle_optimization(need_create_task=False)
assert task.editor_data_json['1']['original_subtitle'] == 'Edited in table'
widget.close()
"""
    )


def test_home_workflow_passes_subtitle_snapshots_in_memory(tmp_path):
    video_path = repr(str(tmp_path / "episode.mp4"))
    _run_qt_script(
        f"""
from videocaptioner.core.asr.asr_data import ASRData, ASRDataSeg
from PyQt5.QtWidgets import QApplication
from videocaptioner.ui.view.home_interface import HomeInterface

app = QApplication([])
widget = HomeInterface()
widget.transcription_interface.process = lambda: None
widget.subtitle_optimization_interface.process = lambda: None
widget.postprocess_interface.process = lambda: None
widget.video_synthesis_interface.process = lambda: None

widget.switch_to_transcription({video_path})
transcribed = ASRData([ASRDataSeg('Original', 0, 2000)])
widget.transcription_interface.task.result_data = transcribed
transcript_path = widget.transcription_interface.task.output_path

widget.switch_to_subtitle_optimization(transcript_path, {video_path})
subtitle_task = widget.subtitle_optimization_interface.task
assert subtitle_task.input_data is transcribed
translated = ASRData([ASRDataSeg('Original', 0, 2000, '译文')])
subtitle_task.result_data = translated

widget.switch_to_postprocess({video_path}, subtitle_task.output_path)
postprocess_task = widget.postprocess_interface.task
assert postprocess_task.input_data is translated
postprocessed = ASRData([ASRDataSeg('Original', 0, 2200, '译文')])
postprocess_task.result_data = postprocessed
postprocess_task.active_subtitle_path = postprocess_task.postprocessed_subtitle_path

widget.switch_to_video_synthesis({video_path}, postprocess_task.active_subtitle_path)
assert widget.video_synthesis_interface.task.input_data is postprocessed
widget.close()
"""
    )


def test_workflow_export_controls_smoke_on_task_and_batch_pages():
    _run_qt_script(
        """
from PyQt5.QtWidgets import QApplication
from videocaptioner.ui.common.config import cfg
from videocaptioner.ui.view.batch_process_interface import BatchProcessInterface
from videocaptioner.ui.view.task_creation_interface import TaskCreationInterface

app = QApplication([])
original_set = cfg.set
cfg.set = lambda *args, **kwargs: None
try:
    for page_type in (TaskCreationInterface, BatchProcessInterface):
        widget = page_type()
        assert widget.export_format_combo.currentText() in {'ASS', 'VTT'}

        widget.auto_export_switch.setChecked(False)
        app.processEvents()
        assert not widget.export_format_combo.isEnabled()
        assert not widget.export_style_combo.isEnabled()

        widget.auto_export_switch.setChecked(True)
        widget.export_format_combo.setCurrentText('VTT')
        app.processEvents()
        assert widget.export_format_combo.isEnabled()
        assert not widget.export_style_combo.isEnabled()

        widget.export_format_combo.setCurrentText('ASS')
        app.processEvents()
        assert widget.export_style_combo.isEnabled()
        widget.close()
finally:
    cfg.set = original_set
"""
    )


def test_postprocess_export_preserves_unsaved_primary_state(tmp_path):
    profile_path = repr(str(tmp_path / "profiles.json"))
    primary_path = repr(str(tmp_path / "postprocessed-source.srt"))
    export_path = repr(str(tmp_path / "delivery.vtt"))
    _run_qt_script(
        f"""
from pathlib import Path
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QFileDialog
from videocaptioner.core.postprocess import PostprocessProfileStore
import videocaptioner.ui.view.postprocess_interface as postprocess_view

app = QApplication([])
postprocess_view.InfoBar.success = lambda *args, **kwargs: None
postprocess_view.InfoBar.error = lambda *args, **kwargs: None
widget = postprocess_view.PostprocessInterface(
    profile_store=PostprocessProfileStore({profile_path})
)
widget.primary_srt_path = {primary_path}
widget.model.update_all({{'1': {{'start_time': 0, 'end_time': 2000,
    'original_subtitle': 'Original', 'translated_subtitle': 'Translation'}}}})
assert widget.model.setData(widget.model.index(0, 2), 'Unsaved edit', Qt.EditRole)
assert widget._dirty

QFileDialog.getSaveFileName = lambda *args, **kwargs: ({export_path}, '')
widget.export_copy('vtt')
assert Path({export_path}).is_file()
assert 'Unsaved edit' in Path({export_path}).read_text(encoding='utf-8')
assert widget._dirty
assert not Path({primary_path}).exists()

assert widget.save_primary_srt(show_feedback=False)
assert not widget._dirty
assert Path({primary_path}).is_file()
widget.close()
"""
    )
